#
# Makefile for proj1
#
#

CXX      = clang++
CXXFLAGS = -g3 std=c++11 -Wall -Wextra
LDFLAGS  = -g3












make: 
	clang++ -std=c++11 -Wall -Wextra DirNode.o FSTree.o hashTable.cpp main.cpp Node.cpp -o grep



provide:
	comp15 proj2part3 hashTable.h hashTable.cpp main.cpp Node.cpp Node.h README Makefile


